# Generated by Django 4.1.7 on 2023-02-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memos',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='memos',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='memos',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='memos', to='apps.labels'),
        ),
    ]
