# Generated by Django 4.1.7 on 2023-02-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_memos_content_alter_memos_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labels',
            new_name='Keywords',
        ),
        migrations.RenameField(
            model_name='keywords',
            old_name='label',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='memos',
            old_name='labels',
            new_name='keywords',
        ),
    ]
